datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sec_kill
  username: root
  password: 12345678

redis:
  database: 0
  host: localhost
  port: 6379

rabbitmq:
  host: localhost
  username: guest
  password: guest
  port: 5672
  virtual-host: /